services:
  - type: web
    name: oyakodontube
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python main.py"
    region: singapore
    envVars:
      - key: FLASK_ENV
        value: production
